import { Inter } from "next/font/google";
import { nunito_sans } from "./utils/fonts";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Blogging App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_sans} >
        <main>{children}</main>
      </body>
    </html>
  );
}
